Make the cache files in a child folder of user document folder on Windows.
Suwayomi/Tachidesk-Sorayomi pull request #216
Opened 2023-08-08 17:09 UTC by hxdhttk

The current location of these cache files may confuse the user since they do not imply any relations to this app, the user may think they are harmful and want to delete them and then find they will be regenerated indeterminately.

Current State:
<img width="942" alt="image" src="https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/17916222/7579689b-3371-4c8b-a3ad-dba82d5fcea9">

This PR:
![image](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/17916222/7a308269-18ed-4ea9-b2fd-147030463643)
![image](https://github.com/Suwayomi/Tachidesk-Sorayomi/assets/17916222/cf7fade1-31d9-4e9e-95fc-30ee793593dd)

2023-08-09 05:45 UTC, DattatreyaReddy commented
Hi @hxdhttk, 
can you use the `path` package to join the paths instead of hardcoding it? 
so we could use this on all platforms instead of only Windows.

```dart
import 'package:path/path.dart' as path;
  Directory? appDirectory;
  if (!kIsWeb) {
    appDirectory = await getApplicationDocumentsDirectory();
    appDirectory = Directory(path.join(appDirectory.path, 'Sorayomi'));
  } else {
    appDirectory = null; // to avoid initialization error I think
  }
```
 something like above?
 you may need to add path package btw!

2023-08-10 11:30 UTC, hxdhttk commented
Hi @DattatreyaReddy,
The PR was updated.

2023-08-10 17:41 UTC, DattatreyaReddy requested changes
Thank you for Raising the PR

2023-08-10 17:41 UTC, DattatreyaReddy commented on lib/main.dart
> +        await File(oldCacheFilePath).rename(newCacheFilePath);
@hxdhttk it seems like rename may not work all times so we can use copy & delete method as mentioned in [official doc](https://api.flutter.dev/flutter/dart-io/File/rename.html#:~:text=rename%20abstract%20method,-Future%20rename&text=Renames%20this%20file.,File%20for%20the%20renamed%20file.&text=On%20some%20platforms%2C%20a%20rename,and%20then%20remove%20the%20original.)

2023-08-10 17:41 UTC, DattatreyaReddy commented on lib/main.dart
> +    appDirectory = Directory(path.join(appDocDirectory.path, 'Sorayomi'));
you can use `packageInfo.appName` as you did in prev [commit](https://github.com/Suwayomi/Tachidesk-Sorayomi/pull/216/commits/3d38941f3a77cd3b7bae4a01e2cc5413e8172ace#diff-e61eb31d013d12616f5532636a88cfa63631dda8f7829e5424e68542214d1608R28)

2023-08-10 17:48 UTC, merged