Feature/trackers
Suwayomi/Tachidesk-Sorayomi pull request #236
Opened 2023-10-16 14:27 UTC by tachimanga

The PR to Tachidesk can be found here: https://github.com/Suwayomi/Tachidesk-Server/pull/720
Note: the OAuth process is based on flutter_web_auth_2 (https://pub.dev/packages/flutter_web_auth_2#setup)
Currently, it only supports iOS and Android if the callback url is suwayomi://oauth/${tracker}

2023-10-16 16:19 UTC, DattatreyaReddy requested changes
I'll merge this PR as soon as Server PR is merged and deployed.

Thank you for Rising PR. ❤️

2023-10-16 16:19 UTC, DattatreyaReddy commented on lib/src/features/settings/presentation/settings/settings_screen.dart
> +          if (Platform.isAndroid || Platform.isIOS)
Also, I don't think the Browser Settings screen is Android or IOS specific.
so maybe this condition needs to be on the tracker Screen

2023-10-16 16:19 UTC, DattatreyaReddy commented on lib/src/features/settings/presentation/tracking/widgets/tracker_list_tile.dart
> +              print("auth err $e");
use `debugPrint` not `print`

2023-10-16 16:19 UTC, DattatreyaReddy commented on lib/src/features/settings/presentation/tracking/widgets/tracker_status_widget.dart
> +                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 8),
use `KEdgeInsets` from `app_sizes.dart` when available

2023-10-16 16:19 UTC, DattatreyaReddy commented on lib/src/features/settings/presentation/tracking/widgets/tracker_status_widget.dart
> +                  borderRadius: BorderRadius.circular(10),
use from `app_sizes.dart`

2023-10-16 16:19 UTC, DattatreyaReddy commented on lib/src/features/settings/presentation/tracking/widgets/tracker_status_widget.dart
> +                  style: Theme.of(context).textTheme.labelLarge?.copyWith(
use `context.textTheme`

2023-10-17 02:24 UTC, tachimanga commented on lib/src/features/settings/presentation/settings/settings_screen.dart
> +          if (Platform.isAndroid || Platform.isIOS)
I have tested it on a web platform, but the callback after OAuth is not successful. Following the instructions in the documentation of flutter_web_auth_2 (https://pub.dev/packages/flutter_web_auth_2#web), I have set up the auth.html file, but it still doesn't work. I suspect that I have to deploy the web app to a cloud service and set the callback URL as http://xxxx.com/auth.html for it to work. However, this approach won't work for iOS and Android platforms to complete the authorization process (their callback URL is suwayomi://oauth/xxx). 
Meanwhile, for Windows and Linux, following the instructions in the flutter_web_auth_2 doc (https://pub.dev/packages/flutter_web_auth_2#windows-and-linux), "There is still a limitation that the callback URL scheme must start with http://localhost:{port}." However, this approach won't work for iOS and Android platforms to complete the authorization process too.

2023-10-17 02:28 UTC, tachimanga commented on lib/src/features/manga_book/presentation/manga_details/widgets/manga_description.dart
> +    final trackerCount = manga.trackers?.where((t) => t.record != null).length;
Great suggestion! I recently learned that the build function in Flutter is called very frequently.

2023-10-17 02:32 UTC, tachimanga commented on lib/src/features/settings/presentation/tracking/controller/tracking_controller.dart
> +  ref.onDispose(token.cancel);
We did send a request to TrackingUrl.list

2023-10-17 04:11 UTC, DattatreyaReddy commented on lib/src/features/settings/presentation/settings/settings_screen.dart
> +          if (Platform.isAndroid || Platform.isIOS)
We could always look into it in further iterations.
Also, I'm talking about the `Platform` condition here. (You have to update as i mentioned above)

2023-10-17 04:13 UTC, DattatreyaReddy commented on lib/src/features/settings/presentation/tracking/controller/tracking_controller.dart
> +  ref.onDispose(token.cancel);
That list have its own cancel token. so we dont need it here.
if you look at your code, you haven't use token. (You created it and disposed it)

2023-10-17 05:47 UTC, tachimanga commented on lib/src/features/settings/presentation/tracking/controller/tracking_controller.dart
> +  ref.onDispose(token.cancel);
i'm stupid, ignore me

2023-10-17 07:07 UTC, DattatreyaReddy commented on lib/src/features/settings/presentation/tracking/tracker_settings_screen.dart
> +                      TrackerListTile(tracker: data![index], refresh: refresh,)));
yep

2023-10-19 06:22 UTC, DattatreyaReddy commented on lib/src/features/settings/presentation/settings/settings_screen.dart
> +          if (Platform.isAndroid || Platform.isIOS)
@tachimanga as I've mentioned above, It seems that the `if` condition is applied on `Browser Tile` rather than `Tracker Screen`. It means that users on the web and desktop can see the `Tracker tile` and cannot see the `Browser Tile`.

Can you plz recheck it and update it?

2024-08-07 00:47 UTC, closed without merging